# Generated by Django 6.0.6 on 2026-06-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DcfCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('ticker', models.CharField(blank=True, max_length=32)),
                ('current_fcf', models.DecimalField(decimal_places=2, max_digits=18)),
                ('growth_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('discount_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('terminal_growth_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('forecast_years', models.PositiveSmallIntegerField(default=5)),
                ('net_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('non_operating_assets', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('shares_outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('enterprise_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('equity_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('value_per_share', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcf_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
