# Generated by Django 6.0.6 on 2026-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcfcalculation',
            name='tag',
            field=models.CharField(blank=True, default='未分类', max_length=80),
        ),
    ]
