# Generated by Django 6.0.6 on 2026-06-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_tags_from_existing_calculations(apps, schema_editor):
    DcfCalculation = apps.get_model('calculator', 'DcfCalculation')
    DcfTag = apps.get_model('calculator', 'DcfTag')

    for calculation in DcfCalculation.objects.all():
        name = (calculation.tag or '未分类').strip() or '未分类'
        DcfTag.objects.get_or_create(user_id=calculation.user_id, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_dcfcalculation_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DcfTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcf_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_dcf_tag_per_user')],
            },
        ),
        migrations.RunPython(create_tags_from_existing_calculations, migrations.RunPython.noop),
    ]
